#!/usr/bin/env python3
"""One-off extractor: mine an existing LibreOffice Draw wiring diagram (.odg)
for the fridge's common infrastructure, and print a draft common.txt.

The ODG canvas is organized like the diagrams this replaces: temperature
plates are vertical bars, and each fridge line is a horizontal row of shapes.
We cluster labeled shapes into rows, order them by x, map x to the nearest
plate, and emit draft `[lines]`/chain text for hand-proofreading.

Usage:
    python3 tools/extract_odg.py wiring_diagram.odg          # human report
    python3 tools/extract_odg.py wiring_diagram.odg --draft  # draft common.txt
"""

import re
import sys
import zipfile
import xml.etree.ElementTree as ET
from collections import defaultdict

DRAW = "urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"
SVG = "urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0"


def cm(v):
    if v is None:
        return None
    v = v.strip()
    for suffix, mul in (("cm", 1.0), ("mm", 0.1), ("in", 2.54), ("pt", 2.54 / 72)):
        if v.endswith(suffix):
            return float(v[: -len(suffix)]) * mul
    return float(v)


def all_text(el):
    return " ".join(t.strip() for t in el.itertext() if t.strip())


def load_shapes(odg_path):
    z = zipfile.ZipFile(odg_path)
    root = ET.fromstring(z.read("content.xml"))
    pages = list(root.iter("{%s}page" % DRAW))
    shapes = []            # (page, x, y, w, h, text)
    for pi, page in enumerate(pages):
        for el in page.iter():
            tag = el.tag.split("}")[1]
            if tag not in ("custom-shape", "frame", "rect"):
                continue
            x = cm(el.get("{%s}x" % SVG))
            y = cm(el.get("{%s}y" % SVG))
            w = cm(el.get("{%s}width" % SVG)) or 0
            h = cm(el.get("{%s}height" % SVG)) or 0
            if x is None or y is None:
                continue
            shapes.append((pi, x + w / 2, y + h / 2, w, h, all_text(el)))
    return shapes


def find_plates(shapes):
    """Plate bars carry labels like '4K Plate'."""
    plates = []
    for pi, x, y, w, h, t in shapes:
        m = re.match(r"^(.*?)\s*Plate$", t)
        if m and pi == 0:
            plates.append((x, m.group(1) or "Top"))
    plates.sort()
    return plates


def guess_token(text, x, plates):
    """Map a shape label to a wiagram chain token."""
    t = text.strip()
    plate = ""
    if plates:
        nearest = min(plates, key=lambda p: abs(p[0] - x))
        if abs(nearest[0] - x) < 6.0:
            plate = "@" + nearest[1]
    if re.match(r"^[+-]?\d+(\.\d+)?\s*dB$", t):
        return t.replace(" ", "") + plate
    if t.lower() == "bulkhead":
        return "bulkhead" + plate
    if t.lower().startswith("hemt"):
        return "hemt(%s)" % t[4:].strip() + plate
    if "circulator" in t.lower():
        return "circ(%s)" % t.replace("Circulator", "").strip() + plate
    if t.lower() in ("db-25", "db25"):
        return "db25" + plate
    if t.lower() == "fischer":
        return "fischer" + plate
    if t.lower() in ("term.", "term"):
        return "term"
    if t.lower() in ("knl", "k&l"):
        return "knl" + plate
    if "eccosorb" in t.lower():
        return "eccosorb" + plate
    if t.lower() == "filter" or t.lower() == "filters":
        return "filter(?)" + plate
    return "?%r" % t


def cluster_rows(shapes, page=0, row_tol=0.32):
    """Group shapes into horizontal rows by y."""
    rows = defaultdict(list)
    keys = []
    for pi, x, y, w, h, t in sorted(shapes, key=lambda s: (s[2], s[1])):
        if pi != page or not t:
            continue
        if h > 8:          # skip plate bars / big boxes
            continue
        placed = False
        for k in keys:
            if abs(k - y) < row_tol:
                rows[k].append((x, t))
                placed = True
                break
        if not placed:
            keys.append(y)
            rows[y].append((x, t))
    return [(k, sorted(rows[k])) for k in sorted(rows)]


LINE_NAME = re.compile(r"^(In \d+|Out [A-Z]|DC \d+(-\d+)?|Pair \d+)$")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    odg = sys.argv[1]
    draft = "--draft" in sys.argv
    shapes = load_shapes(odg)
    plates = find_plates(shapes)

    if not draft:
        print("Plates (x_cm, name):")
        for x, name in plates:
            print("  %7.2f  %s" % (x, name))
        print("\nRows (page 1):")
        for y, items in cluster_rows(shapes):
            names = [t for _x, t in items]
            print("  y=%7.2f  %s" % (y, "  |  ".join(names)))
        return 0

    # --- draft common.txt ---
    print("# DRAFT common.txt generated by tools/extract_odg.py from %s" % odg)
    print("# Proofread before use!\n")
    print("[plates]")
    for _x, name in plates:
        print("%s: ?" % name)
    print()
    chains = {}
    for y, items in cluster_rows(shapes):
        name = None
        toks = []
        for x, t in items:
            if LINE_NAME.match(t) and name is None:
                name = t
            else:
                toks.append(guess_token(t, x, plates))
        if name and toks:
            chains[name] = toks
    for name, toks in chains.items():
        print("# %s: %s" % (name, " -> ".join(toks)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
